import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { FlatCompat } from '@eslint/eslintrc';
import { globalIgnores } from 'eslint/config';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// eslint-config-next@15.x ships only legacy (eslintrc) configs: it has no
// `exports` map and no `flat` entry, so the flat config is built by
// translating `next/core-web-vitals` + `next/typescript` with FlatCompat.
// Plugins must be resolved from inside the eslint-config-next package so they
// are found under pnpm's strict node_modules layout.
const nextPackageDir = path.dirname(
  fileURLToPath(import.meta.resolve('eslint-config-next/package.json')),
);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  resolvePluginsRelativeTo: nextPackageDir,
});

export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  globalIgnores([
    '**/node_modules/**',
    '**/.next/**',
    '**/out/**',
    '**/dist/**',
    '.atl/**',
    '.codegraph/**',
    'dev.out.log',
    // Generated by `next dev` / `next build` (says "do not edit") and rewritten
    // on every run, so it can never carry a source-level fix.
    '**/next-env.d.ts',
  ]),
];
