import 'server-only';

import { hash, verify, type Options } from '@node-rs/argon2';

/**
 * argon2id parameters.
 *
 * OWASP Password Storage Cheat Sheet recommends argon2id with a minimum of
 * 19 MiB of memory, 2 iterations, and a parallelism of 1. These are the
 * minimums, used as the explicit floor rather than as a ceiling.
 *
 * WHY EXACTLY THESE VALUES, and why each one is a decision rather than a default:
 *
 * - `memoryCost: 19456` (19 MiB) — OWASP's floor. This is the parameter that
 *   actually does the work: memory-hardness is what makes a hash expensive to
 *   attack with GPUs and ASICs, which are abundant and parallel. Going higher is
 *   a real option but a memory *ceiling* decision as well, because every
 *   concurrent login holds this much RAM. 19 MiB is the number that is both
 *   OWASP-compliant and safe on the smallest server we will plausibly run on.
 *
 * - `timeCost: 2` — OWASP's floor. Iterations are the second lever, and unlike
 *   memory they cost CPU rather than capacity, so they are the cheaper knob to
 *   turn. Two is OWASP's stated minimum for argon2id.
 *
 * - `parallelism: 1` — OWASP's floor, and the most important of the three for
 *   this choice. Hashing libraries spawn `parallelism` threads at the *same*
 *   memory cost, so `parallelism: 4` would mean four times the RAM and four times
 *   the CPU for the same 19 MiB profile. It also multiplies the cost of a
 *   concurrent login storm, which is precisely the attack argon2id exists to make
 *   expensive.
 *
 * THE REAL CONSTRAINT IS NOT PASSWORD STRENGTH. It is that `hash()` is
 * intentionally slow, which makes authentication a denial-of-service amplifier.
 * An endpoint that will burn 19 MiB and two passes per request must be rate
 * limited server-side — see `docs/security.md` §6. A slow hash without a rate
 * limit is a worse outage than a fast hash on a strong password.
 *
 * `@node-rs/argon2` is used rather than `argon2` or `bcrypt`: it ships **prebuilt
 * binaries** for Windows, macOS and Linux, so the setup path never needs
 * `node-gyp` or Visual Studio Build Tools. `bcrypt` is additionally not
 * memory-hard. See ADR 0002.
 */

/**
 * `Algorithm.Argon2id` as a literal.
 *
 * `@node-rs/argon2` declares `Algorithm` as an **ambient `const enum`**
 * (`export declare const enum Algorithm { Argon2id = 2 }` in `index.d.ts`).
 * TypeScript forbids referencing an ambient const enum when
 * `verbatimModuleSyntax` is on, which this project enables. Importing the value
 * therefore fails to compile, even though the enum is also exported at runtime
 * (`module.exports.Algorithm = nativeBinding.Algorithm`).
 *
 * The literal is used instead, with the value checked against the enum's member
 * type at the point of use — see `ARGON2ID_OPTIONS`, where `satisfies` fails to
 * compile if the literal is ever changed to something `Algorithm` does not allow
 * (for example `1`, which is Argon2i).
 */
const ARGON2ID = 2;

/**
 * `satisfies` (not a cast) so that changing the literal to a value `Algorithm`
 * does not define — `1` for Argon2i, say — is a compile error rather than a
 * silently weaker hash.
 */
const ARGON2ID_OPTIONS = {
  algorithm: ARGON2ID,
  memoryCost: 19456, // 19 MiB — OWASP minimum
  timeCost: 2, // iterations — OWASP minimum
  parallelism: 1, // OWASP minimum
} satisfies Options;

/**
 * Hashes a plaintext password for storage.
 *
 * The salt is generated by the argon2 library and embedded in the returned
 * string along with the parameters, so `verify` needs nothing but the hash. That
 * is what makes raising `memoryCost` later a migration of *new* hashes rather
 * than a re-hash of the whole table — the old hashes stay verifiable because
 * they carry their own parameters.
 *
 * Parameters belong in the hash, not in a table column: a column makes "which
 * parameters are these?" a question only the application can answer, and a
 * database dump then loses the information needed to verify anything.
 */
export async function hashPassword(password: string): Promise<string> {
  return hash(password, ARGON2ID_OPTIONS);
}

/**
 * Verifies a password against a stored hash.
 *
 * `verify` is constant-time inside the argon2 implementation. Do not add an
 * equality check of your own anywhere near this function.
 */
export async function verifyPassword({
  hash: hashedPassword,
  password,
}: {
  hash: string;
  password: string;
}): Promise<boolean> {
  // A malformed or truncated hash makes the argon2 library throw. That must be
  // a `false`, not a crash: a row with an unreadable hash should deny access, not
  // turn into a 500 that tells an attacker they found something interesting.
  try {
    return await verify(hashedPassword, password, ARGON2ID_OPTIONS);
  } catch {
    return false;
  }
}

/** Exported for the auth module's documentation and for tests. */
export const ARGON2ID_PARAMETERS = ARGON2ID_OPTIONS;
